name: Main CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  spec_biome:
    name: Run Biome in /spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src
        working-directory: packages/spec

  utils_biome:
    name: Run Biome in /utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src
        working-directory: packages/utils

  utils_vitest:
    name: Run Vitest in /utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Run Vitest
        run: pnpm test
        working-directory: packages/utils
